include:
- ./func/*
kind: ArchiveUploadSpec
name: func-bvlh

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: onboarding-steps-br-fn-bd3fd88d-1ca6-451b-86ba-aa66dd50de2f
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: onboarding-steps-br-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-bvlh
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-06-27T19:42:11Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: onboarding-steps-br-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: onboarding-steps-br-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_onboarding_step_br
    packageref:
      name: onboarding-steps-br-fn-bd3fd88d-1ca6-451b-86ba-aa66dd50de2f
      namespace: default
  requestsPerPod: 100000
  resources: {}
