apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 6532cf70-6210-4817-9764-dbbb8c68d727
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: onboarding-steps-br-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /onboarding_steps_br
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /onboarding_steps_br
