apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 0d2e9f90-3dd0-4e16-a3e8-cc2f7581aa9a
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: onb-br-steps-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /onboarding/steps_br
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /onboarding/steps_br
